/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TiHackSearchBox {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTiHackSearchBoxElement extends Components.TiHackSearchBox, HTMLStencilElement {
    }
    var HTMLTiHackSearchBoxElement: {
        prototype: HTMLTiHackSearchBoxElement;
        new (): HTMLTiHackSearchBoxElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "ti-hack-search-box": HTMLTiHackSearchBoxElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TiHackSearchBox {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "ti-hack-search-box": TiHackSearchBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "ti-hack-search-box": LocalJSX.TiHackSearchBox & JSXBase.HTMLAttributes<HTMLTiHackSearchBoxElement>;
        }
    }
}
